SERVICE_ACCOUNT_CREDENTIALS = './sa.json'
SERVICE_ACCOUNT_SCOPES = ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive']
BASE_FOLDER = "1mM9Xn39B_TFVWspZlT2DyQViSwBnOJ-F"
TEAMS_SHEET_NAME = "Squadre"
MATCHES_SHEET_NAME = "Partite"
CLASSIFICATION_SHEET_NAME = "Classifica"
SPREADSHEET_NAME = 'Torneo super Bello'
ORIGINAL_SPREADSHEET_ID = "16aBDYLq6w4nd0Bc63brYlgRdveM2tGhiImRDvh4cOS4"
RANGE_TEAM_NAMES = "!B1:B"
ATTRIBUTO_NOME_SQUADRA = 'Nome'
